### ISSUE TITLE
Insufficient permissions with setup from README

### ISSUE THREAD

**Issue by FriedrichFroebel** [author/action-rollback#17]
I am using the action with the recommended configuration:

```yaml
      - name: Delete old Pre-Release
        uses: author/action-rollback@master
        with:
          tag: prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This seems to fail with an error:

```
Warning: HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/author/action-rollback/master/dist/index.js:5581:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (/home/runner/work/_actions/author/action-rollback/master/dist/index.js:24677:22)
Error: Resource not accessible by integration
```

Adding

```yaml
    permissions:
      contents: write
```

to the corresponding job solved it for me, thus it seems like the current docs are outdated here?

**Comment by coreybutler** [comment]
Yes, outdated docs. Thanks for bringing it to my attention.
